### PR TITLE
Aspect ratio preserved and cancel block

### PR DESCRIPTION
**Pull request by ntnmrndn**
Hi,

Sorry, I must have mixed up somewhere ... 

This code includes everything discussed including the cleanup !

### CODE REVIEW

**Comment by lucasecf** [comment]
@ntnmrndn Nice!

About the `photoRejectedBlock`, I just notice a different behaviour from the `photoAcceptedBlock`. 

I implemented this one as a simply callback, always calling the `dismissViewControllerAnimated` at the end of the action.

But your implementation of the `photoRejectedBlock` has a slightly different behaviour. When the block exists, the controller will not be dismissed, i. e. it's the user responsibility to dismiss the controller in the  block implementation.

So we have two options. Either we change the photoAcceptedBlock implementation to be similar as the photoRejectedBlock or vice versa.

What do you think?

Ps: you don't need to create a new PR for this change, you can commit-push in this same remote branch you created (aspectRatioPreservedAndCancelBlock), I think.

**Comment by lucasecf** [comment]
Merged the PR, I'll implement the changes I told myself :)

**Comment by ntnmrndn** [comment]
Actually I need the  viewController to stay on screen while I upload the avatar. This is also the behavior of the UIImagePickerViewController.
I didn't changed the behavior of the other method to avoid breaking compatibility for other LECropPictureViewController.

**Comment by lucasecf** [comment]
We can change the behaviour of the other block and lauch a new major version, to avoid break compatibilities for the ones who are using the `~> 0.1.1` syntax. And I don't really think there's already much people using the component anyways, its still with zero stars.

Before creating this new major version, do you have any suggestions of features to include?

**Comment by ntnmrndn** [comment]
Yes, iPad landscape is broken (possibly iPhone landscape too).

I won't be working on this project for our next sprint, so I can't make a pull request any time soon.

**Comment by lucasecf** [comment]
For bugs like that you can create issues here in github. I can take a look in them myself.

**Pull request merged**
